### ISSUE TITLE
Visual feedback on Confrim/reject

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-sysui-chrome-extension#3]

**Comment by goldylucks** [comment]
which errors r could b returned from parity upon confirming/rejecting?

confirming:
1. invalid password
2. bad data ?

rejecting:
1. bad data?

**Comment by tomusdrw** [comment]
For now:
Confirming:
1. Hash / false
2. If you mean incorrect parameters than yes. (like you forgot to send a password or sth like this)

Rejecting:
1. true / false
2. Bad parameters (forgot to put confirmationId)
